import os
env = Environment(ENV = {'TERM' : os.environ['TERM'], 'PATH' : os.environ['PATH']},
        CPPPATH = '/usr/local/homebrew/include/', CXXFLAGS="-std=c++11", CXX="distcc g++")
env.Library('libtntdetail.a', ['timeout_pool.cpp'])
